server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-cloud-gateway
eureka:
  client:
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
      show-components: always